Make container cluster work for both routes-based and autopilot clusters
For autopilot clusters, the networking is pre-configured. With container
gen-client, we want to send `IPAllocationPolicy.UseIpAliases` and `IPAllocationPolicy.UseRoutes` as false,
so that the service can pick the default IP allocation mode [1].

Only when the `networkingMode` is specifically set to "ROUTES",
`IPAllocationPolicy.UseRoutes` is passed with true.

This change fixes the following error when apply an autopilot cluster

```
resource "google_container_cluster" "tf-cluster" {
  name     = "tf-cluster"
  location = "europe-west1"
  project = "my-project"

  enable_autopilot = "true"
  release_channel {
    channel = "REGULAR"
  }
  min_master_version = "1.21.5-gke.1302"
}
```

```
zgoogle_container_cluster.tf-cluster: Creating...

Error: googleapi: Error 400: Max pods constraint on node pools for Autopilot clusters should be 32., badRequest

  on container_cluster.tf line 1, in resource "google_container_cluster" "tf-cluster":
   1: resource "google_container_cluster" "tf-cluster" {

```