ci: add missing pathspec dependency for yamllint pipeline (#10269)
pipelines for YAML lints are failing due to:
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/yamllint", line 5, in <module>
    from yamllint.cli import run
  File "/home/runner/.local/lib/python3.10/site-packages/yamllint/cli.py", line 24, in <module>
    from yamllint.config import YamlLintConfig, YamlLintConfigError
  File "/home/runner/.local/lib/python3.10/site-packages/yamllint/config.py", line 19, in <module>
    import pathspec
ModuleNotFoundError: No module named 'pathspec'
```

A fresh install in a virtual environment using the following command:
```bash
$ pip install yamllint==1.32.0 pyyaml==6.0.1
$ pip freeze
pathspec==0.12.1
PyYAML==6.0.1
yamllint==1.32.0
```

Regression introduced by 60917c85e2f6645e21846fcf0197ff18244c747d